#!/bin/bash
# @file To start nodejs program
# @author guillain (guillain@gmail.com)
# @license LGPL-3.0
# @settings:
# @@ dev
# @@ prod
#

SCRIPT=${2}
echo ${SCRIPT}
APP=`basename ${SCRIPT}`
ROOT_DIR=`dirname ${0}`
LOG_DIR="${ROOT_DIR}/log"

help="\n- Arg 1: action = start | stop | restart | status | log\n- Arg 2: script = ./app/myscript.js\nIE: ${0} start app/slack.js"

if [ "${1}" == "" ]; then echo -e "No argument provided. ${help}"; exit 1; fi
if [ "${2}" == "" ]; then echo -e "Two arg are required. ${help}"; exit 1; fi

# For the manual mode and the tunneling
# * ngrok http 80 
# or
# * lt -s mytest -p 80

# For Google Auth
export GOOGLE_APPLICATION_CREDENTIALS="app/botkit-translator-b7ea4b1a1405.json"

cd "${ROOT_DIR}"

case $1 in
  start)
    pm2 start "${SCRIPT}" \
    --log    "${LOG_DIR}/all.log" \
    --output "${LOG_DIR}/app.log" \
    --error  "${LOG_DIR}/err.log" \
    --merge-logs \
    --log-date-format="YYYY-MM-DD HH:mm Z";;
  stop)
    pm2 stop "${SCRIPT}";;
  restart)
    $0 stop ${SCRIPT}
    $0 start ${SCRIPT}
    ;;
  show)
    pm2 show "${APP}";;
  status)
    pm2 status "${APP}";;
  log)
    pm2 log "${APP}";;
  manual)
    DEBUG=* node "${SCRIPT}";;
  *) echo -e "Command not found. ${help}"; exit 1;;
esac

exit 0
